### ISSUE TITLE
How about hide the tk_istream_t implementation into the .c file?

### ISSUE THREAD

**Issue by suzp1984** [zlgopen/tkc#4]
https://github.com/zlgopen/tkc/blob/1c776292f038821cb7cb6f1dc16265943b9f9655/src/streams/buffered/istream_buffered.h#L30

Take `istream_buffered` as example: why not hide the `tk_istream_buffered_t` to the `istream_buffered.c`? Don't let the user aware the impl details. I notice all the streams related impl has same issue.

**Comment by xianjimli** [comment]
完全隐藏从理论上确实更好。我的考虑是：1. TKC/AWTK 是开源软件，不需要二进制兼容。2.隐藏实现后，调试器里也看不到需要的信息，影响调试效率。3.所有公开属性不可直接修改，未标记可读的属性不可读取。只要开发者遵循这个习惯，并无大碍。4.直接读取属性，运行效率更高。

总之，各有优缺点吧。

**Comment by suzp1984** [comment]
明白，为了理解上面几点，还有几个疑问确认下：
**3. 这里指的是doc里面的声明吧**
```

/**
 * @class tk_ostream_file_t
 * @parent tk_ostream_t
 *
 * 基于文件实现的输出流。
 *
 */
struct _tk_ostream_file_t {
  tk_ostream_t ostream;

  fs_file_t* file;
};
```
这里的 `@class @parent` 是用来生成api doc用的吧，这个是那个规范，或者说是用那个工具生成doc?
**4. 直接读取属性，运行效率更高**
这里是指上面的 `fs_file_t* file` 可以直接读取而无需通过一个方法么 (例如 `tk_ostream_file_get_file`)

**Comment by xianjimli** [comment]
这个属性没有用@property标记，外部不能访问，也不会出现在生成的文档中。
